package com.example.temporalproducer.model.enums;

/** "A spelled out enumeration name uniquely identifying the product." */
public enum ProductEnum {
  BOOKING_SERVICES("BOOKING_SERVICES"),
  SUPPLY_CHAIN_ORCHESTRATOR("SUPPLY_CHAIN_ORCHESTRATOR"),
  COLD_CHAIN_MANAGEMENT("COLD_CHAIN_MANAGEMENT"),
  COLD_CHAIN_SOLUTIONS("COLD_CHAIN_SOLUTIONS"),
  COLD_STORAGE("COLD_STORAGE"),
  CONTRACT_FLAT("CONTRACT_FLAT"),
  CONTRACT_INCENTIVE("CONTRACT_INCENTIVE"),
  CONTRACT_SEASONAL("CONTRACT_SEASONAL"),
  CONTRACT_SPORADIC("CONTRACT_SPORADIC"),
  CONTRACT_UNLIMITED("CONTRACT_UNLIMITED"),
  CUSTOMS_CLEARANCE("CUSTOMS_CLEARANCE"),
  CUSTOMER_DEDICATED_DEPOT("CUSTOMER_DEDICATED_DEPOT"),
  EXPORT_CONTAINER_SERVICES("EXPORT_CONTAINER_SERVICES"),
  FULL_CONTAINER_STORAGE("FULL_CONTAINER_STORAGE"),
  IMPORT_CONTAINER_SERVICES("IMPORT_CONTAINER_SERVICES"),
  E_DELIVERY("E_DELIVERY"),
  MAERSK_E_FULFILMENT("MAERSK_E_FULFILMENT"),
  MAERSK_INLAND_HUB("MAERSK_INLAND_HUB"),
  VALUE_PROTECT("VALUE_PROTECT"),
  IMPORT_INTERMODAL_MULTICARRIER("IMPORT_INTERMODAL_MULTICARRIER"),
  EXPORT_INTERMODAL_MULTICARRIER("EXPORT_INTERMODAL_MULTICARRIER");

  private final String productEnumValue;

  ProductEnum(String productEnum) {
    this.productEnumValue = productEnum;
  }

  public String getProductEnumValue() {
    return productEnumValue;
  }
}
