package com.example.temporalproducer.model.enums;

import lombok.AllArgsConstructor;

/** + Transport mode enum value, e.g. MOTHER_VESSEL, AIR, TRUCK, BARGE or MULTI_MODAL */
@AllArgsConstructor
public enum TransportModeEnum {
  MARITIME("MARITIME"),
  RAIL("RAIL"),
  RAIL_INLAND_DEPOT("RAIL_INLAND_DEPOT"),
  ROAD("ROAD"),
  AIR("AIR"),
  MULTI_MODAL("MULTI_MODAL"),
  INLAND_WATER("INLAND_WATER"),
  OCEAN("OCEAN"),
  VESSEL_SHARING_FEEDER_VESSEL("VESSEL_SHARING_FEEDER_VESSEL"),
  MOTHER_VESSEL("MOTHER_VESSEL"),
  VESSEL_SHARING_MOTHER_VESSEL("VESSEL_SHARING_MOTHER_VESSEL"),
  FEEDER("FEEDER"),
  FOREIGN_FEEDER_VESSEL("FOREIGN_FEEDER_VESSEL"),
  OWNED_FEEDER_VESSEL("OWNED_FEEDER_VESSEL"),
  BARGE("BARGE"),
  BARGE_COMBINED("BARGE_COMBINED"),
  TRUCK("TRUCK"),
  SEA("SEA"),
  ROAD_AND_AIR_COMBINED("ROAD_AND_AIR_COMBINED"),
  RAIL_AND_ROAD_COMBINED("RAIL_AND_ROAD_COMBINED"),
  RAIL_AND_AIR_COMBINED("RAIL_AND_AIR_COMBINED"),
  SEA_AND_AIR_COMBINED("SEA_AND_AIR_COMBINED"),
  SEA_AND_ROAD_COMBINED("SEA_AND_ROAD_COMBINED"),

  SEA_AND_RAIL_COMBINED("SEA_AND_RAIL_COMBINED"),
  COMBINED("COMBINED");

  private final String transportModeEnumValue;

  public String getTransportModeEnumValue() {
    return transportModeEnumValue;
  }
}
